version: "2"

services:
    nginx:
        build: ./w-nginx
        links: 
            - app:app
        ports:
            - "80:80"
    app:
        build: .
        expose:
            - "5000"
        command: python -u /whitespace/w-app/app.py
        depends_on:
            - db
    db:
        image: mongo:3.4.2
        
