version: "2"

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./w-nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
    app:
        build: .
        command: python -u /whitespace/w-app/app.py
        ports:
            - "5000:5000"
        volumes:
            - ./w-app:/whitespace/w-app
        depends_on:
            - db
    db:
        image: mongo:3.4.2
        
